before_script:
  - rm -rf "*-env"; virtualenv -p python3 ${CI_JOB_ID}-env
  - ${CI_JOB_ID}-env/bin/pip3 install -r requirements.txt

after_script:
  - 'killall --user $USER'
  - rm -rf ${CI_JOB_ID}-env

stages:
  - style_guide_checks

Flake8Checks:
  stage: style_guide_checks
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - ${CI_JOB_ID}-env/bin/flake8
  allow_failure: true
