before_script:
  - rm -rf "*-env"; virtualenv -p python3 ${CI_JOB_ID}-env
  - ${CI_JOB_ID}-env/bin/pip3 install -r requirements.txt

after_script:
  - 'killall --user $USER'
  - rm -rf ${CI_JOB_ID}-env

stages:
  - style_guide_checks
  - pypi_deploy

Flake8Checks:
  stage: style_guide_checks
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - ${CI_JOB_ID}-env/bin/flake8
  allow_failure: false

Deploy:
  stage: pypi_deploy
  tags:
    - CI_TrackPerformanceLRZ
  only:
      - master
  script:
    - ${CI_JOB_ID}-env/bin/python3 -m pip install --upgrade setuptools wheel
    - ${CI_JOB_ID}-env/bin/python3 setup.py sdist bdist_wheel
    - ${CI_JOB_ID}-env/bin/pip3 install --upgrade twine
    - ${CI_JOB_ID}-env/bin/python3 -m twine upload --repository-url ${PYPI_SERVER} --username ${PYPI_USER} --password ${PYPI_PASSWORD} dist/*
  allow_failure: false
